import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/Header';
import HeaderGradient from '../components/HeaderGradient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className=' z-1 flex flex-col' data-theme='dark'>
        <Header />
        <HeaderGradient />
        {children}
      </body>
    </html>
  );
}
